substitutions:  
  name: "localbytes-bulb"  
  friendly_name: "LocalBytes RGBCT Bulb"
  device_comment: "ESPHome for LocalBytes Bulb, Firmware config by MichaelMKKelly."
  wifi_min_auth: "WPA"
  wifi_fast_connect: "false"
  ipv6_enable: "true"
  sntp_update_interval: 6h
  sntp_server_1: "0.pool.ntp.org"
  sntp_server_2: "1.pool.ntp.org"
  sntp_server_3: "2.pool.ntp.org"
  timezone: ""
  color_interlock: "true"
  power_limit: 1.0

  minimal_only: false
  main_yaml: !include
    file: main.yaml
packages:
  minimal_yaml_file: !include minimal.yaml
  main_yaml_file: ${ main_yaml if not minimal_only else {} }

dashboard_import:
  package_import_url: github://MichaelMKKelly/ESPHome-Config-for-localbytes-bulb-9w-rgbct/base.yaml