substitutions:  
  name: "localbytes-bulb"  
  friendly_name: "LocalBytes RGBCT Bulb"
  version_number: "1.1.1"
  device_comment: "ESPHome for LocalBytes Bulb, Firmware config by MichaelMKKelly."
  wifi_min_auth: "WPA"
  wifi_fast_connect: "false"
  ipv6_enable: "true"
  sntp_update_interval: 6h
  sntp_server_1: "0.pool.ntp.org"
  sntp_server_2: "1.pool.ntp.org"
  sntp_server_3: "2.pool.ntp.org"
  timezone: ""
  color_interlock: "true"
  power_limit: 1.0

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  friendly_name: "${friendly_name}"
  comment: "${device_comment}"
  project:
    name: "MichaelMKKelly.localbytes-bulb-9w-rgbct"
    version: "${version_number}"
  min_version: 2026.3.0
  on_boot:
      then:
        - script.execute: fast_boot_script
        - select.set_index:
            id: power_mode
            index: !lambda |-
                    return id(restore_mode)-1;
        - lambda: |-
              switch(id(restore_mode))
              {
              case 1:{
                      auto call = id(bulb).turn_off();                      
                      call.set_color_mode(ColorMode::COLD_WARM_WHITE );
                      call.set_cold_white(1);
                      call.set_warm_white(0);
                      call.perform();
                      break;
                      }
              case 2:{
                      auto call = id(bulb).turn_on();
                      call.set_brightness(1.0);
                      call.set_transition_length(500);
                      call.set_color_mode(ColorMode::COLD_WARM_WHITE );
                      call.set_cold_white(1);
                      call.set_warm_white(0);
                      call.perform();
                      break;
                      }
              default:{
                      break;
                      }
              }

dashboard_import:
  package_import_url: github://MichaelMKKelly/ESPHome-Config-for-localbytes-bulb-9w-rgbct/localbytes-bulb.yaml@main

esp8266:
  board: esp8285
  restore_from_flash: true

#Disabled for Production firmware as not needed and saves firmware size and system memory for stability 
#logger:

api:

ota:
  - platform: esphome
  - platform: http_request

http_request:
  verify_ssl: False
  tls_buffer_size_rx: 16384

update:
  - platform: http_request
    name: "ESPHome for LocalBytes Bulb"
    id: firmwareupdate
    source: https://michaelmkkelly.github.io/ESPHome-Config-for-localbytes-bulb-9w-rgbct/updatemanifest.json

factory_reset:
  resets_required: 7
  max_delay: 10s

safe_mode:
  
wifi:
  ap:
    ssid: "${friendly_name}"
  min_auth_mode: "${wifi_min_auth}"
  fast_connect: "${wifi_fast_connect}"
  
network:
  enable_ipv6: "${ipv6_enable}"

captive_portal:

globals:
  - id: fast_boot
    type: int
    restore_value: yes
    initial_value: '0'

  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: "1"

time:
  - platform: sntp
    id: sntp_time
    timezone: "${timezone}"
    update_interval: ${sntp_update_interval}
    servers:
      - "${sntp_server_1}"
      - "${sntp_server_2}"
      - "${sntp_server_3}"
    on_time_sync:
      then:        
        - if:
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'

select:
  - platform: template
    name: "Power On Default State"
    id: "power_mode"
    optimistic: true
    options:
      - Always Off
      - Always On
      - Restore Power Off State
    on_value:
      then:
        - lambda: |-
            id(restore_mode)=i+1;

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    disabled_by_default: true

button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    id: Reset
    entity_category: config
    disabled_by_default: true

  - platform: safe_mode
    name: "Safe Mode"
    internal: false
    entity_category: config
    disabled_by_default: true

  - platform: template
    name: "Check for updates"
    entity_category: diagnostic
    disabled_by_default: True
    id: update_button
    on_press: 
      then:
        - update.check: firmwareupdate 

  - platform: template
    name: "Firmware - Flash Forced Update"
    entity_category: diagnostic
    disabled_by_default: True
    on_press: 
        - ota.http_request.flash:
            url:  https://michaelmkkelly.github.io/ESPHome-Config-for-localbytes-bulb-9w-rgbct/latest-binary/localbytes-bulb.bin.gz
            md5_url: https://michaelmkkelly.github.io/ESPHome-Config-for-localbytes-bulb-9w-rgbct/latest-binary/localbytes-bulb.bin.gz.md5
  - platform: template
    name: "Firmware - Flash Installer Tool"
    entity_category: diagnostic
    disabled_by_default: True
    on_press: 
      then:
        - ota.http_request.flash:
            url: https://michaelmkkelly.github.io/ESPHome-Config-for-localbytes-bulb-9w-rgbct/bulb-installer-tool/latest-binary/lb-bulb-installer.bin.gz
            md5_url: https://michaelmkkelly.github.io/ESPHome-Config-for-localbytes-bulb-9w-rgbct/bulb-installer-tool/latest-binary/lb-bulb-installer.bin.gz.md5
  
output:
  - platform: esp8266_pwm
    id: red
    pin: GPIO4
    min_power: 0.000499
    max_power: ${power_limit}
    zero_means_zero: true
    
  - platform: esp8266_pwm
    id: green
    pin: GPIO12
    min_power: 0.000499
    max_power: ${power_limit}
    zero_means_zero: true
    
  - platform: esp8266_pwm
    id: blue
    pin: GPIO14
    min_power: 0.000499
    max_power: ${power_limit}
    zero_means_zero: true
    
  - platform: esp8266_pwm
    id: cold_white
    pin: GPIO5
    min_power: 0.000499
    max_power: ${power_limit}
    zero_means_zero: true
    
  - platform: esp8266_pwm
    id: warm_white
    pin: GPIO13
    min_power: 0.000499
    max_power: ${power_limit}
    zero_means_zero: true

light:
  - platform: rgbww
    name: "Lightbulb"
    id: bulb
    restore_mode: RESTORE_DEFAULT_ON
    warm_white: warm_white
    cold_white: cold_white
    red: red
    green: green
    blue: blue    
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    constant_brightness: True
    color_interlock: "${color_interlock}"    

    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 2s
      - pulse:
          name: "Asymmetrical Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
      - random:
      - strobe:      
      - flicker:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic
      disabled_by_default: true  
  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic

script:
  - id: fast_boot_script
    then:
      - if:
          condition:
            lambda: return ( id(fast_boot) >= 3 );
          then:
            - lambda: |-
                ESP_LOGD("localbytes-bulb.yaml", "Now the counter is greater than or equal to 3, perform reset device and reboot");
                id(fast_boot) = 0;
                fast_boot->loop();
                global_preferences->sync();
                auto call = id(bulb).turn_on();
                call.set_transition_length(500);
                call.set_brightness(1.0);
                call.set_color_mode(ColorMode::COLD_WARM_WHITE );
                call.set_cold_white(1);
                call.set_warm_white(0);

            - delay: 5s
            - button.press: Reset
      - lambda: |-
          id(fast_boot) += 1;
          fast_boot->loop();
          global_preferences->sync();
          ESP_LOGD("localbytes-bulb.yaml", "Now the counter is %d.  Reset the device when the counter is greater than or equal to 3", id(fast_boot));
      - delay: 10s
      - lambda: |-
          ESP_LOGD("localbytes-bulb.yaml", "Reset counter");
          id(fast_boot) = 0;
          fast_boot->loop();
          global_preferences->sync();